#ifndef _DRIVER_I2S_H
#define _DRIVER_I2S_H

#ifdef CONFIG_DRIVER_I2S

#define REG_I2S_BASE_ADDR               (0x00F10000UL)
#define I2S_CHANNEL_NUMBER_ALL          1
#define I2S_CHANNEL_NUMBER_MAX          (I2S_CHANNEL_NUMBER_ALL - 1)
#define I2S_CHANNEL_NUMBER_MIN          0


#define REG_I2S_CONTRL_ADDR             (REG_I2S_BASE_ADDR + 0 * 4)
#define REG_I2S_CONTRL_MASK             0xFFFFFFFFUL
#define REG_I2S_CONTRL                  (*((volatile unsigned long *) REG_I2S_CONTRL_ADDR))

#define I2S_CONTRL_BIT_RATE_POSI        0
#define I2S_CONTRL_BIT_RATE_MASK        (0x00FFUL << I2S_CONTRL_BIT_RATE_POSI)

#define I2S_CONTRL_SAMPLE_RATE_POSI     8
#define I2S_CONTRL_SAMPLE_RATE_MASK     (0x1FUL << I2S_CONTRL_SAMPLE_RATE_POSI)

#define I2S_CONTRL_PCM_DLEN_POSI        13
#define I2S_CONTRL_PCM_DLEN_MASK        (0x07UL << I2S_CONTRL_PCM_DLEN_POSI)

#define I2S_CONTRL_DATA_LEN_POSI        16
#define I2S_CONTRL_DATA_LEN_MASK        (0x1FUL << I2S_CONTRL_DATA_LEN_POSI)

#define I2S_CONTRL_SYNC_LEN_POSI        21
#define I2S_CONTRL_SYNC_LEN_MASK        (0x07UL << I2S_CONTRL_SYNC_LEN_POSI)

#define I2S_CONTRL_LSB_FIRST_POSI       24
#define I2S_CONTRL_LSB_FIRST_MASK       (0x01UL << I2S_CONTRL_LSB_FIRST_POSI)
#define I2S_CONTRL_LSB_FIRST_CLEAR      (0x00UL << I2S_CONTRL_LSB_FIRST_POSI)
#define I2S_CONTRL_LSB_FIRST_SET        (0x01UL << I2S_CONTRL_LSB_FIRST_POSI)

#define I2S_CONTRL_SCLK_INV_POSI        25
#define I2S_CONTRL_SCLK_INV_MASK        (0x01UL << I2S_CONTRL_SCLK_INV_POSI)
#define I2S_CONTRL_SCLK_INV_CLEAR       (0x00UL << I2S_CONTRL_SCLK_INV_POSI)
#define I2S_CONTRL_SCLK_INV_SET         (0x01UL << I2S_CONTRL_SCLK_INV_POSI)

#define I2S_CONTRL_LRCKRP_POSI          26
#define I2S_CONTRL_LRCKRP_MASK          (0x01UL << I2S_CONTRL_LRCKRP_POSI)
#define I2S_CONTRL_LRCKRP_CLEAR         (0x00UL << I2S_CONTRL_LRCKRP_POSI)
#define I2S_CONTRL_LRCKRP_SET           (0x01UL << I2S_CONTRL_LRCKRP_POSI)

#define I2S_CONTRL_MODE_SEL_POSI        27
#define I2S_CONTRL_MODE_SEL_MASK        (0x07UL << I2S_CONTRL_MODE_SEL_POSI)

#define I2S_CONTRL_MASTER_ENABLE_POSI   30
#define I2S_CONTRL_MASTER_ENABLE_MASK   (0x01UL << I2S_CONTRL_MASTER_ENABLE_POSI)
#define I2S_CONTRL_MASTER_ENABLE_CLEAR  (0x00UL << I2S_CONTRL_MASTER_ENABLE_POSI)
#define I2S_CONTRL_MASTER_ENABLE_SET    (0x01UL << I2S_CONTRL_MASTER_ENABLE_POSI)

#define I2S_CONTRL_I2S_PCM_ENABLE_POSI  31
#define I2S_CONTRL_I2S_PCM_ENABLE_MASK  (0x01UL << I2S_CONTRL_I2S_PCM_ENABLE_POSI)
#define I2S_CONTRL_I2S_PCM_ENABLE_CLEAR (0x00UL << I2S_CONTRL_I2S_PCM_ENABLE_POSI)
#define I2S_CONTRL_I2S_PCM_ENABLE_SET   (0x01UL << I2S_CONTRL_I2S_PCM_ENABLE_POSI)


#define REG_I2S_CONFIG_ADDR             (REG_I2S_BASE_ADDR + 1 * 4)
#define REG_I2S_CONFIG_MASK             0x000FFFFFUL
#define REG_I2S_CONFIG                  (*((volatile unsigned long *) REG_I2S_CONFIG_ADDR))

#define I2S_CONFIG_RX_INT_ENABLE_POSI   0
#define I2S_CONFIG_RX_INT_ENABLE_MASK   (0x01UL << I2S_CONFIG_RX_INT_ENABLE_POSI)
#define I2S_CONFIG_RX_INT_ENABLE_CLEAR  (0x00UL << I2S_CONFIG_RX_INT_ENABLE_POSI)
#define I2S_CONFIG_RX_INT_ENABLE_SET    (0x01UL << I2S_CONFIG_RX_INT_ENABLE_POSI)

#define I2S_CONFIG_TX_INT0_ENABLE_POSI  1
#define I2S_CONFIG_TX_INT0_ENABLE_MASK  (0x01UL << I2S_CONFIG_TX_INT0_ENABLE_POSI)
#define I2S_CONFIG_TX_INT0_ENABLE_CLEAR (0x00UL << I2S_CONFIG_TX_INT0_ENABLE_POSI)
#define I2S_CONFIG_TX_INT0_ENABLE_SET   (0x01UL << I2S_CONFIG_TX_INT0_ENABLE_POSI)

#define I2S_CONFIG_TX_INT1_ENABLE_POSI  2
#define I2S_CONFIG_TX_INT1_ENABLE_MASK  (0x01UL << I2S_CONFIG_TX_INT1_ENABLE_POSI)
#define I2S_CONFIG_TX_INT1_ENABLE_CLEAR (0x00UL << I2S_CONFIG_TX_INT1_ENABLE_POSI)
#define I2S_CONFIG_TX_INT1_ENABLE_SET   (0x01UL << I2S_CONFIG_TX_INT1_ENABLE_POSI)

#define I2S_CONFIG_TX_INT2_ENABLE_POSI  3
#define I2S_CONFIG_TX_INT2_ENABLE_MASK  (0x01UL << I2S_CONFIG_TX_INT2_ENABLE_POSI)
#define I2S_CONFIG_TX_INT2_ENABLE_CLEAR (0x00UL << I2S_CONFIG_TX_INT2_ENABLE_POSI)
#define I2S_CONFIG_TX_INT2_ENABLE_SET   (0x01UL << I2S_CONFIG_TX_INT2_ENABLE_POSI)

#define I2S_CONFIG_RX_OVF_ENABLE_POSI   4
#define I2S_CONFIG_RX_OVF_ENABLE_MASK   (0x01UL << I2S_CONFIG_RX_OVF_ENABLE_POSI)
#define I2S_CONFIG_RX_OVF_ENABLE_CLEAR  (0x00UL << I2S_CONFIG_RX_OVF_ENABLE_POSI)
#define I2S_CONFIG_RX_OVF_ENABLE_SET    (0x01UL << I2S_CONFIG_RX_OVF_ENABLE_POSI)

#define I2S_CONFIG_TX_UDF0_ENABLE_POSI  5
#define I2S_CONFIG_TX_UDF0_ENABLE_MASK  (0x01UL << I2S_CONFIG_TX_UDF0_ENABLE_POSI)
#define I2S_CONFIG_TX_UDF0_ENABLE_CLEAR (0x00UL << I2S_CONFIG_TX_UDF0_ENABLE_POSI)
#define I2S_CONFIG_TX_UDF0_ENABLE_SET   (0x01UL << I2S_CONFIG_TX_UDF0_ENABLE_POSI)

#define I2S_CONFIG_TX_UDF1_ENABLE_POSI  6
#define I2S_CONFIG_TX_UDF1_ENABLE_MASK  (0x01UL << I2S_CONFIG_TX_UDF1_ENABLE_POSI)
#define I2S_CONFIG_TX_UDF1_ENABLE_CLEAR (0x00UL << I2S_CONFIG_TX_UDF1_ENABLE_POSI)
#define I2S_CONFIG_TX_UDF1_ENABLE_SET   (0x01UL << I2S_CONFIG_TX_UDF1_ENABLE_POSI)

#define I2S_CONFIG_TX_UDF2_ENABLE_POSI  7
#define I2S_CONFIG_TX_UDF2_ENABLE_MASK  (0x01UL << I2S_CONFIG_TX_UDF2_ENABLE_POSI)
#define I2S_CONFIG_TX_UDF2_ENABLE_CLEAR (0x00UL << I2S_CONFIG_TX_UDF2_ENABLE_POSI)
#define I2S_CONFIG_TX_UDF2_ENABLE_SET   (0x01UL << I2S_CONFIG_TX_UDF2_ENABLE_POSI)

#define I2S_CONFIG_RX_FIFO_LEVEL_POSI   8
#define I2S_CONFIG_RX_FIFO_LEVEL_MASK   (0x03UL << I2S_CONFIG_RX_FIFO_LEVEL_POSI)
#define I2S_CONFIG_RX_FIFO_LEVEL_SET_8  (0x00UL << I2S_CONFIG_RX_FIFO_LEVEL_POSI)
#define I2S_CONFIG_RX_FIFO_LEVEL_SET_16 (0x01UL << I2S_CONFIG_RX_FIFO_LEVEL_POSI)
#define I2S_CONFIG_RX_FIFO_LEVEL_SET_24 (0x02UL << I2S_CONFIG_RX_FIFO_LEVEL_POSI)

#define I2S_CONFIG_TX_FIFO0_LEVEL_POSI   10
#define I2S_CONFIG_TX_FIFO0_LEVEL_MASK   (0x03UL << I2S_CONFIG_TX_FIFO0_LEVEL_POSI)
#define I2S_CONFIG_TX_FIFO0_LEVEL_SET_8  (0x00UL << I2S_CONFIG_TX_FIFO0_LEVEL_POSI)
#define I2S_CONFIG_TX_FIFO0_LEVEL_SET_16 (0x01UL << I2S_CONFIG_TX_FIFO0_LEVEL_POSI)
#define I2S_CONFIG_TX_FIFO0_LEVEL_SET_24 (0x02UL << I2S_CONFIG_TX_FIFO0_LEVEL_POSI)

#define I2S_CONFIG_TX_FIFO1_LEVEL_POSI   12
#define I2S_CONFIG_TX_FIFO1_LEVEL_MASK   (0x03UL << I2S_CONFIG_TX_FIFO1_LEVEL_POSI)
#define I2S_CONFIG_TX_FIFO1_LEVEL_SET_8  (0x00UL << I2S_CONFIG_TX_FIFO1_LEVEL_POSI)
#define I2S_CONFIG_TX_FIFO1_LEVEL_SET_16 (0x01UL << I2S_CONFIG_TX_FIFO1_LEVEL_POSI)
#define I2S_CONFIG_TX_FIFO1_LEVEL_SET_24 (0x02UL << I2S_CONFIG_TX_FIFO1_LEVEL_POSI)

#define I2S_CONFIG_TX_FIFO2_LEVEL_POSI   14
#define I2S_CONFIG_TX_FIFO2_LEVEL_MASK   (0x03UL << I2S_CONFIG_TX_FIFO2_LEVEL_POSI)
#define I2S_CONFIG_TX_FIFO2_LEVEL_SET_8  (0x00UL << I2S_CONFIG_TX_FIFO2_LEVEL_POSI)
#define I2S_CONFIG_TX_FIFO2_LEVEL_SET_16 (0x01UL << I2S_CONFIG_TX_FIFO2_LEVEL_POSI)
#define I2S_CONFIG_TX_FIFO2_LEVEL_SET_24 (0x02UL << I2S_CONFIG_TX_FIFO2_LEVEL_POSI)

#define I2S_CONFIG_RX_FIFO_CLEAR_POSI   16
#define I2S_CONFIG_RX_FIFO_CLEAR_MASK   (0x01UL << I2S_CONFIG_RX_FIFO_CLEAR_POSI)

#define I2S_CONFIG_TX_FIFO0_CLEAR_POSI  17
#define I2S_CONFIG_TX_FIFO0_CLEAR_MASK  (0x01UL << I2S_CONFIG_TX_FIFO0_CLEAR_POSI)

#define I2S_CONFIG_TX_FIFO1_CLEAR_POSI  18
#define I2S_CONFIG_TX_FIFO1_CLEAR_MASK  (0x01UL << I2S_CONFIG_TX_FIFO1_CLEAR_POSI)

#define I2S_CONFIG_TX_FIFO2_CLEAR_POSI  19
#define I2S_CONFIG_TX_FIFO2_CLEAR_MASK  (0x01UL << I2S_CONFIG_TX_FIFO2_CLEAR_POSI)


#define REG_I2S_STATUS_ADDR             (REG_I2S_BASE_ADDR + 2 * 4)
#define REG_I2S_STATUS_MASK             0x0000FFFFUL
#define REG_I2S_STATUS                  (*((volatile unsigned long *) REG_I2S_STATUS_ADDR))

#define I2S_STATUS_RX_INT_FLAG_POSI     0
#define I2S_STATUS_RX_INT_FLAG_MASK     (0x01UL << I2S_STATUS_RX_INT_FLAG_POSI)

#define I2S_STATUS_TX_INT0_FLAG_POSI    1
#define I2S_STATUS_TX_INT0_FLAG_MASK    (0x01UL << I2S_STATUS_TX_INT0_FLAG_POSI)

#define I2S_STATUS_TX_INT1_FLAG_POSI    2
#define I2S_STATUS_TX_INT1_FLAG_MASK    (0x01UL << I2S_STATUS_TX_INT1_FLAG_POSI)

#define I2S_STATUS_TX_INT2_FLAG_POSI    3
#define I2S_STATUS_TX_INT2_FLAG_MASK    (0x01UL << I2S_STATUS_TX_INT2_FLAG_POSI)

#define I2S_STATUS_RX_OVF_FLAG_POSI     4
#define I2S_STATUS_RX_OVF_FLAG_MASK     (0x01UL << I2S_STATUS_RX_OVF_FLAG_POSI)

#define I2S_STATUS_TX_UDF0_FLAG_POSI    5
#define I2S_STATUS_TX_UDF0_FLAG_MASK    (0x01UL << I2S_STATUS_TX_UDF0_FLAG_POSI)

#define I2S_STATUS_TX_UDF1_FLAG_POSI    6
#define I2S_STATUS_TX_UDF1_FLAG_MASK    (0x01UL << I2S_STATUS_TX_UDF1_FLAG_POSI)

#define I2S_STATUS_TX_UDF2_FLAG_POSI    7
#define I2S_STATUS_TX_UDF2_FLAG_MASK    (0x01UL << I2S_STATUS_TX_UDF2_FLAG_POSI)

#define I2S_STATUS_RX_FIFO_EMPTY_POSI           8
#define I2S_STATUS_RX_FIFO_EMPTY_MASK           (0x01UL << I2S_STATUS_RX_FIFO_EMPTY_POSI)

#define I2S_STATUS_RX_FIFO_ALMOST_EMPTY_POSI    9
#define I2S_STATUS_RX_FIFO_ALMOST_EMPTY_MASK    (0x01UL << I2S_STATUS_RX_FIFO_ALMOST_EMPTY_POSI)

#define I2S_STATUS_TX_FIFO0_FULL_POSI           10
#define I2S_STATUS_TX_FIFO0_FULL_MASK           (0x01UL << I2S_STATUS_TX_FIFO0_FULL_POSI)

#define I2S_STATUS_TX_FIFO0_ALMOST_FULL_POSI    11
#define I2S_STATUS_TX_FIFO0_ALMOST_FULL_MASK    (0x01UL << I2S_STATUS_TX_FIFO0_ALMOST_FULL_POSI)

#define I2S_STATUS_TX_FIFO1_FULL_POSI           12
#define I2S_STATUS_TX_FIFO1_FULL_MASK           (0x01UL << I2S_STATUS_TX_FIFO1_FULL_POSI)

#define I2S_STATUS_TX_FIFO1_ALMOST_FULL_POSI    13
#define I2S_STATUS_TX_FIFO1_ALMOST_FULL_MASK    (0x01UL << I2S_STATUS_TX_FIFO1_ALMOST_FULL_POSI)

#define I2S_STATUS_TX_FIFO2_FULL_POSI           14
#define I2S_STATUS_TX_FIFO2_FULL_MASK           (0x01UL << I2S_STATUS_TX_FIFO2_FULL_POSI)

#define I2S_STATUS_TX_FIFO2_ALMOST_FULL_POSI    15
#define I2S_STATUS_TX_FIFO2_ALMOST_FULL_MASK    (0x01UL << I2S_STATUS_TX_FIFO2_ALMOST_FULL_POSI)


#define REG_I2S_DATA0_ADDR              (REG_I2S_BASE_ADDR + 3 * 4)
#define REG_I2S_DATA0_MASK              0xFFFFFFFFUL
#define REG_I2S_DATA0                   (*((volatile unsigned long *) REG_I2S_DATA0_ADDR))


#define REG_I2S_DATA1_ADDR              (REG_I2S_BASE_ADDR + 4 * 4)
#define REG_I2S_DATA1_MASK              0xFFFFFFFFUL
#define REG_I2S_DATA1                   (*((volatile unsigned long *) REG_I2S_DATA1_ADDR))


#define REG_I2S_DATA2_ADDR              (REG_I2S_BASE_ADDR + 5 * 4)
#define REG_I2S_DATA2_MASK              0xFFFFFFFFUL
#define REG_I2S_DATA2                   (*((volatile unsigned long *) REG_I2S_DATA2_ADDR))


#define REG_I2S_CONFIG2_ADDR            (REG_I2S_BASE_ADDR + 6 * 4)
#define REG_I2S_CONFIG2_MASK            0x000000F7UL
#define REG_I2S_CONFIG2                 (*((volatile unsigned long *) REG_I2S_CONFIG2_ADDR))

#define I2S_CONFIG2_DOWN_SAMP_RATIO_POSI	0
#define I2S_CONFIG2_DOWN_SAMP_RATIO_MASK	(0x07UL << I2S_CONFIG2_DOWN_SAMP_RATIO_POSI)

#define I2S_CONFIG2_BIT_SEQ_MODE_POSI		4
#define I2S_CONFIG2_BIT_SEQ_MODE_MASK		(0x03UL << I2S_CONFIG2_BIT_SEQ_MODE_POSI)

#define I2S_CONFIG2_TX_FIFO_MODE_POSI		6
#define I2S_CONFIG2_TX_FIFO_MODE_MASK		(0x03UL << I2S_CONFIG2_TX_FIFO_MODE_POSI)

void i2s_init(unsigned long smp_ratio, unsigned char role, unsigned char data_width, unsigned char mode_sel);
void i2s_enable(void);
void i2s_disable(void);
void i2s_clrfifo(unsigned char fifo_idx);
void i2s_isr(void);

#endif
#endif
